<#
.SYNOPSIS
    Build script for protected release with anti-reverse engineering measures.

.DESCRIPTION
    This script compiles the project with maximum protection settings:
    - Fat LTO for code merging
    - Symbol stripping
    - Optional UPX packing
    - Binary signing and integrity hash generation

.PARAMETER BinaryName
    Name of the binary to build (default: uses crate name)

.PARAMETER Features
    Cargo features to enable (default: "full,integrity-check")

.PARAMETER SkipUpx
    Skip UPX compression (useful if UPX not installed)

.PARAMETER SignBinary
    Generate integrity signature for the binary

.PARAMETER PrivateKeyPath
    Path to private key for signing (PEM format)

.EXAMPLE
    .\build_protected.ps1
    .\build_protected.ps1 -SkipUpx
    .\build_protected.ps1 -SignBinary -PrivateKeyPath "keys\private.pem"
#>

param(
    [string]$BinaryName = "",
    [string]$Features = "full,integrity-check",
    [switch]$SkipUpx,
    [switch]$SignBinary,
    [string]$PrivateKeyPath = "keys\private.pem",
    [switch]$Verbose
)

$ErrorActionPreference = "Stop"

# Colors for output
function Write-Step { param($msg) Write-Host "[*] $msg" -ForegroundColor Cyan }
function Write-Success { param($msg) Write-Host "[+] $msg" -ForegroundColor Green }
function Write-Warning { param($msg) Write-Host "[!] $msg" -ForegroundColor Yellow }
function Write-Error { param($msg) Write-Host "[-] $msg" -ForegroundColor Red }

# Get crate name from Cargo.toml if not specified
if (-not $BinaryName) {
    $cargoToml = Get-Content "Cargo.toml" -Raw
    if ($cargoToml -match 'name\s*=\s*"([^"]+)"') {
        $BinaryName = $matches[1]
    } else {
        Write-Error "Could not determine binary name from Cargo.toml"
        exit 1
    }
}

$targetDir = "target\release-protected"
$binaryPath = "$targetDir\$BinaryName.exe"
$signaturePath = "$targetDir\$BinaryName.sig"
$hashPath = "$targetDir\$BinaryName.sha256"

Write-Host ""
Write-Host "========================================" -ForegroundColor Magenta
Write-Host "  Protected Release Build Script" -ForegroundColor Magenta
Write-Host "========================================" -ForegroundColor Magenta
Write-Host ""

# Step 1: Clean previous protected build
Write-Step "Cleaning previous protected build..."
if (Test-Path $targetDir) {
    Remove-Item -Recurse -Force $targetDir -ErrorAction SilentlyContinue
}

# Step 2: Build with protected profile
Write-Step "Building with release-protected profile..."
Write-Host "  Features: $Features" -ForegroundColor DarkGray

$env:RUSTFLAGS = "-C target-feature=+crt-static"

$cargoArgs = @(
    "build",
    "--profile", "release-protected",
    "--features", $Features
)

if ($Verbose) {
    $cargoArgs += "-v"
}

& cargo $cargoArgs

if ($LASTEXITCODE -ne 0) {
    Write-Error "Cargo build failed!"
    exit 1
}

Write-Success "Build completed successfully"

# Get binary size
$originalSize = (Get-Item $binaryPath).Length
Write-Host "  Original size: $([math]::Round($originalSize / 1MB, 2)) MB" -ForegroundColor DarkGray

# Step 3: UPX compression (optional)
if (-not $SkipUpx) {
    Write-Step "Compressing with UPX..."

    $upxPath = Get-Command upx -ErrorAction SilentlyContinue
    if ($upxPath) {
        # Create backup
        Copy-Item $binaryPath "$binaryPath.original"

        & upx --best --lzma $binaryPath 2>$null

        if ($LASTEXITCODE -eq 0) {
            $compressedSize = (Get-Item $binaryPath).Length
            $ratio = [math]::Round(($compressedSize / $originalSize) * 100, 1)
            Write-Success "UPX compression: $([math]::Round($compressedSize / 1MB, 2)) MB ($ratio% of original)"
        } else {
            Write-Warning "UPX compression failed, using original binary"
            Copy-Item "$binaryPath.original" $binaryPath
        }

        Remove-Item "$binaryPath.original" -ErrorAction SilentlyContinue
    } else {
        Write-Warning "UPX not found in PATH, skipping compression"
        Write-Host "  Install UPX: https://github.com/upx/upx/releases" -ForegroundColor DarkGray
    }
}

# Step 4: Generate integrity hash
Write-Step "Generating integrity hash..."
$hash = (Get-FileHash $binaryPath -Algorithm SHA256).Hash
$hash | Out-File $hashPath -Encoding ASCII -NoNewline
Write-Success "SHA256: $hash"

# Step 5: Generate Rust include file for embedded hash
$hashIncludePath = "src\generated\binary_hash.rs"
$hashIncludeDir = Split-Path $hashIncludePath
if (-not (Test-Path $hashIncludeDir)) {
    New-Item -ItemType Directory -Path $hashIncludeDir -Force | Out-Null
}

@"
//! Auto-generated binary integrity hash
//! Generated by build_protected.ps1 at $(Get-Date -Format "yyyy-MM-dd HH:mm:ss")
//! DO NOT EDIT MANUALLY

/// SHA256 hash of the protected binary (before this hash was embedded)
pub const BINARY_HASH: &str = "$hash";

/// Build timestamp
pub const BUILD_TIMESTAMP: &str = "$(Get-Date -Format "yyyy-MM-ddTHH:mm:ssZ")";

/// Build profile used
pub const BUILD_PROFILE: &str = "release-protected";
"@ | Out-File $hashIncludePath -Encoding UTF8

Write-Success "Generated hash include file: $hashIncludePath"

# Step 6: Sign binary (optional)
if ($SignBinary) {
    Write-Step "Signing binary..."

    if (-not (Test-Path $PrivateKeyPath)) {
        Write-Warning "Private key not found at: $PrivateKeyPath"
        Write-Host "  Generate keys with: openssl genrsa -out keys\private.pem 2048" -ForegroundColor DarkGray
        Write-Host "                      openssl rsa -in keys\private.pem -pubout -out keys\public.pem" -ForegroundColor DarkGray
    } else {
        # Sign the hash with private key
        $opensslPath = Get-Command openssl -ErrorAction SilentlyContinue
        if ($opensslPath) {
            & openssl dgst -sha256 -sign $PrivateKeyPath -out $signaturePath $binaryPath

            if ($LASTEXITCODE -eq 0) {
                Write-Success "Binary signed: $signaturePath"

                # Generate public key if it doesn't exist
                $publicKeyPath = $PrivateKeyPath -replace "private", "public"
                if (-not (Test-Path $publicKeyPath)) {
                    & openssl rsa -in $PrivateKeyPath -pubout -out $publicKeyPath 2>$null
                    Write-Success "Public key generated: $publicKeyPath"
                }
            } else {
                Write-Warning "Signing failed"
            }
        } else {
            Write-Warning "OpenSSL not found, skipping signing"
        }
    }
}

# Summary
Write-Host ""
Write-Host "========================================" -ForegroundColor Magenta
Write-Host "  Build Summary" -ForegroundColor Magenta
Write-Host "========================================" -ForegroundColor Magenta
Write-Host ""
Write-Host "  Binary:    $binaryPath" -ForegroundColor White
Write-Host "  Size:      $([math]::Round((Get-Item $binaryPath).Length / 1MB, 2)) MB" -ForegroundColor White
Write-Host "  Hash:      $hashPath" -ForegroundColor White
if ($SignBinary -and (Test-Path $signaturePath)) {
    Write-Host "  Signature: $signaturePath" -ForegroundColor White
}
Write-Host ""

Write-Host "Protection measures applied:" -ForegroundColor Yellow
Write-Host "  [x] Fat LTO (code merging)" -ForegroundColor Green
Write-Host "  [x] Single codegen unit" -ForegroundColor Green
Write-Host "  [x] Symbol stripping" -ForegroundColor Green
Write-Host "  [x] Panic abort (no unwinding info)" -ForegroundColor Green
Write-Host "  [x] Size optimization (pattern obscuring)" -ForegroundColor Green
if (-not $SkipUpx -and (Get-Command upx -ErrorAction SilentlyContinue)) {
    Write-Host "  [x] UPX LZMA compression" -ForegroundColor Green
} else {
    Write-Host "  [ ] UPX compression (skipped)" -ForegroundColor DarkGray
}
if ($SignBinary -and (Test-Path $signaturePath)) {
    Write-Host "  [x] Binary signature" -ForegroundColor Green
} else {
    Write-Host "  [ ] Binary signature (skipped)" -ForegroundColor DarkGray
}

Write-Host ""
Write-Success "Protected build completed!"
